#server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: teste_java
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddlAuto: update
    properties:
      hibernate.format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace